apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: apka
  name: apka
spec:
  clusterIP: 10.106.100.169
  clusterIPs:
  - 10.106.100.169
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: apka
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.106.100.169
