apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: apka
  name: apka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apka
    spec:
      containers:
        - name: apka
          image: apka:1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: APKA_PORT
              value: "3000"
